[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@latest --activate",
  "pnpm install --frozen-lockfile --prod"
]

[start]
cmd = "mkdir -p logs && pnpm start"
